### PR TITLE
Add starting message to migrations

### PR DESCRIPTION
**Pull request by synbot**
## Currently only "DONE" messages are printed during migrations
When errors occur, it is difficult to find what the next migration might be.

### Acceptance Criteria
1. Logs a "STARTING" message before executing each migration

### Tasks
- Add another writeln in RunMigrationsCommand

### CODE REVIEW

**Comment by baohx2000** [comment]
:star: bonus: execution times & total migrations time

**Comment by paulstatezny** [comment]
Nice! What do you think of removing the name / datestamp of the migration on the "DONE" printout? (Since it's redundant.)

**Comment by spruce-bruce** [comment]
:recycle:

**Comment by baohx2000** [comment]
:recycle:

**Comment by paulstatezny** [comment]
:+1:

**Comment by baohx2000** [comment]
:zero:

**Pull request merged**
