### PR TITLE
Update PHPUnit

### PR DESCRIPTION
**Pull request by synbot**
~~PHPUnit config using wrong attribute keys~~

~~`reportUselessTests` should be `beStrictAboutTestsThatDoNotTestAnything`~~
~~`strictCoverage` should be `checkForUnintentionallyCoveredCode`~~
~~`disallowTestOutput` should be `beStrictAboutOutputDuringTests`~~

Update PHPUnit

### CODE REVIEW

**Comment by paulstatezny** [comment]
:recycle:

**Comment by zpchavez** [comment]
:recycle:

**Comment by paulstatezny** [comment]
You crossed out the changes to the phpunit.xml attribute names, but they're still committed to this issue.

Are those changes still valid/required after updating PHPUnit?

**Comment by paulstatezny** [comment]
:+1:

**Pull request merged**
