### PR TITLE
Allow for better file naming in migrations

### PR DESCRIPTION
**Pull request by synbot**
## Currently, migration files start with the description followed by the date which is unsortable
Making the files start with a constant string (as classes cannot begin with an integer), followed by the date will allow them to be sortable alphabetically.

### Acceptance Criteria
1. New migration files are created in a way which sorting by filename shows them in the order they were created.

### Tasks
- Modify CreateMigrationCommand:classname method to use format:
Migration[datetimestamp][PascalCasedDescription]

### CODE REVIEW

**Comment by spruce-bruce** [comment]
:recycle:

**Comment by spruce-bruce** [comment]
Looks good, will approve after refresh (unless we're waiting to merge this for some reason?)

**Comment by baohx2000** [comment]
:recycle:

**Comment by paulstatezny** [comment]
:+1:

**Comment by baohx2000** [comment]
:zero:

**Pull request merged**
