### PR TITLE
Make EmailService more generic

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. The function prototype for `EmailService::setMailMapper()` will no longer specify EmailMapper and will instead specify AbstractMapper.
1. `createFromArray()` method will use the entity returned from the mapper's `getPrototype()` method instead of `EmailEntity`
1. The prototype for `enqueueSendEmailJob()` will require `AbstractEntity` instead of `EmailEntity`

### CODE REVIEW

**Comment by spruce-bruce** [comment]
:star:

**Comment by baohx2000** [comment]
:hand:

**Comment by baohx2000** [comment]
:+1:

**Comment by spruce-bruce** [comment]
:zero:

**Pull request merged**
