### PR TITLE
Add createdDatetimeColumn and updatedDatetimeColumn to AbstractMapper

### PR DESCRIPTION
**Pull request by synbot**
## Add createdDatetimeColumn and updatedDatetimeColumn to AbstractMapper

They will work the same as `createdTimestampColumn` and `updatedTimestampColumn`, only the value set will be a datetime.

### Acceptance Criteria
1. Dev Tested

### Tasks
- Add properties.
- Update InserterTrait and UpdaterTrait.
- Maybe add a comment saying the timestamp properties are deprecated.

### Additional Notes
- {{list additional notes here, remove if not applicable}}

### CODE REVIEW

**Comment by baohx2000** [comment]
:interrobang: these should be unit tested

**Comment by zpchavez** [comment]
:star:

**Comment by paulstatezny** [comment]
Why are we not just replacing the timestamp ones here? To support both options I guess??

**Comment by zpchavez** [comment]
We could make it a version 2 change and do that

**Comment by baohx2000** [comment]
we can just remove the timestamp stuff as of v2

**Comment by baohx2000** [comment]
Shouldn't last updated be set on insert as well?  Doesn't look like we were doing that with timestamps at this time, but doing so makes it much easier to sort records regardless of if they've ever been updated or not.

**Comment by zpchavez** [comment]
I wouldn't expect that to happen. I don't think that's how MySQL does it.

**Comment by baohx2000** [comment]
:+1:

**Comment by zpchavez** [comment]
:one:

**Pull request merged**
