### PR TITLE
Add High-Level Documentation for this Repo

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria

The README file documents the following in a very concise manner. The goal is for the document to be long enough to explain the important stuff in sufficient detail, but no longer than that.

1. How to set up a project with synapse-base (this is a Silex app bootstrapper)
1. Expectations of synapse-base
 - Environment variables: `APP_ENV`
 - Constants set: `APPDIR`
 - MySQL server set up
 - Redis server set up for job queues
 - Specific config files: db, init, resque, log, install, email
1. How to setup config files correctly.
1. How database installs and migrations work
1. How authentication/authorization work. (Basically a link to the Symfony Security docs and a sentence or two about it.)
1. Utility classes
 - `Arr`
 - `DataObject`
1. A note about the test helpers

### Tasks
- Document those things

### Additional Notes
- Bob and Chris asked me to try to document any "siloed" knowledge I have. This is in part an attempt at that, with regard to synapse base.

### CODE REVIEW

**Comment by nearengine** [comment]
:o:

**Comment by paulstatezny** [comment]
:star:

**Comment by paulstatezny** [comment]
:star:

**Comment by zpchavez** [comment]
:pray:

**Comment by pcavagna** [comment]
:+1:

**Pull request merged**
